
/*****************************************
/* Name:Alba Maloff
/* Course: CIS 4020 01N
/* Semester: Fall 2016
/* Assignment: Program 7 - GUI
/* Date started: November 10,2016 
/* Date finished: November 14, 2016
/*
/* Description: This program creates a GUI Application that lets the user play the game of Rock-Paper-Scissors-Lizard-Spock.
 */
/****************************************/

package application;		 //javafx application package

import java.util.Random; 	 //import statements
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.image.Image;


//Class: GUIController Class
//Description: This class consists of the controller skeleton, the mouse events, and the other methods that help select the users choice
//the computers choice.
public class GUIController {
	
    private Image rockI; 							//declares the image variables
    private Image paperI;	
    private Image scissorsI;	
    private Image lizardI;	
    private Image spockI;	

    @FXML											//Variables initialized as FXML for the SceneBuilder objects (buttons, Imageview, labels)
    private Button scissors_button;

    @FXML
    private ImageView scissors_image;

    @FXML
    private Button spock_button;

    @FXML
    private ImageView spock_image;

    @FXML
    private Button lizard_button;

    @FXML
    private ImageView lizard_image;

    @FXML
    private Button rock_button;

    @FXML
    private ImageView rock_image;

    @FXML
    private Button paper_button;

    @FXML
    private ImageView paper_image;

    @FXML
    private Button clear_button;

    @FXML
    private ImageView user_display;

    @FXML
    private ImageView computer_display;

    @FXML
    private Label winner_statement;
    
    @FXML
    private Label who_wins;

    @FXML													//Variables are initialized as FXML 
    void playersChoiceLizard(MouseEvent event) {			//on click
    	user_display.setImage(lizardI);						//user display placeholder will show the lizard jpg
    	winnerMethod(4);									//Calls the winner method for the user choice and holds the parameter of the item clicked
    }

	@FXML													//Variables are initialized as FXML
    void playersChoicePaper(MouseEvent event) {				//on click
		user_display.setImage(paperI);						//user display placeholder will show the paper jpg
    	winnerMethod(1);									//Calls the winner method for the user choice and holds the parameter of the item clicked
    }

    @FXML													//Variables are initialized as FXML
    void playersChoiceRock(MouseEvent event) {				//on click
    	user_display.setImage(rockI);						//user display placeholder will show the rock jpg
    	winnerMethod(0);									//Calls the winner method for the user choice and holds the parameter of the item clicked
    }

    @FXML													//Variables are initialized as FXML
    void playersChoiceScissors(MouseEvent event) {			//on click	
    	user_display.setImage(scissorsI);					//user display placeholder will show the scissors jpg
    	winnerMethod(2);									//Calls the winner method for the user choice and holds the parameter of the item clicked
    }

    @FXML													//Variables are initialized as FXML
    void playersChoiceSpock(MouseEvent event) {				//on click
    	user_display.setImage(spockI);						//user display placeholder will show the spock jpg
    	winnerMethod(3);									//Calls the winner method for the user choice and holds the parameter of the item clicked
    }

  //Class: Initialize Method
  //Description: This method initializes the variables as new image objects and links them to their jpg files
    public void initialize(){
    	
    	rockI = new Image("rock.jpg");
    	paperI = new Image("paper.jpg");
    	scissorsI = new Image("scissors.jpg");
    	lizardI = new Image("lizard.jpg");
    	spockI = new Image("spock.jpg");

    }
  
    	//Class: autogeneratedChoice Method
    	//Description: This method contains the switch that will assign the object (rock/paper etc) to a case number. 
    	//It also returns the randomNumber that exhibits the random choice made
   		public int autogeneratedChoice(){
    	
    	Random randomNum = new Random();				//Create random object
        int randomNumber = randomNum.nextInt(4);		
        
        String choice = null;							//Declares and initializes choice 
        
        switch(randomNumber){							//randomNumber switch statement
        case 0: choice = "Rock";						//Switch that will assign the object (rock/paper etc) to a case number. 
        	computer_display.setImage(rockI);
            break;
        case 1: choice = "Paper";
        	computer_display.setImage(paperI);
            break;
        case 2: choice = "Scissors";
        	computer_display.setImage(scissorsI);
            break;
        case 3: choice = "Spock";
        	computer_display.setImage(spockI);
        	break;
        case 4: choice = "Lizard";
        	computer_display.setImage(lizardI);
        }
        return randomNumber;							//Returns the randomNumber that exhibits the random choice made
        }
   		
    	/*********************************************************************************************************************
    	/* Class: winnerMethod Method
    	/*Description: This method contains the switch statement that will:
    	/*  1. compare the userchoices to the computer choices 
    	/*  2. declare if the user is a winner, a loser or tied with the computer  
    	*/
    	/**********************************************************************************************************************/

   		public void winnerMethod(int userChoice){
   			
   			int compChoice = autogeneratedChoice(); 			//saves the random number obtained by the call of the autogeneratedChoice
		   														//method in the variable compChoice
   			
   			switch(userChoice){									//switch statement that compares the user choices to the computer choice
   			case 0: 											//case 0 - rock
   				if (compChoice == 0){
   					who_wins.setText("Rock ties Rock");			//set text in a label in the Scene Builder to tell who wins
   					winner_statement.setText("Tie!");			//set text in a label in the Scene Builder to print the status statement
   				}												//The same is true for the rest of the switch statement cases
   				else if (compChoice == 1){
   					who_wins.setText("Paper covers Rock");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 2){
   					who_wins.setText("Rock crushes Scissors");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else if (compChoice == 3){
   					who_wins.setText("Spock vaporizes Rock");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else {
   					who_wins.setText("Rock crushes Lizard");	
   					winner_statement.setText("You are the Winner!");
   				}
   				break;											//break to avoid infinite loop
   				
   			case 1: 											//case 1 - paper
   				if (compChoice == 0){
   					who_wins.setText("Paper covers Rock");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else if (compChoice == 1){
   					who_wins.setText("Paper ties Paper");	
   					winner_statement.setText("Tie!");
   				}
   				else if (compChoice == 2){
   					who_wins.setText("Scissor cuts Paper");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 3){
   					who_wins.setText("Paper disproves Spock");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else {
   					who_wins.setText("Lizard eats Paper");	
   					winner_statement.setText("You are the Loser!");
   				}
   				break;											//break to avoid infinite loop
   			
   			case 2: 											//case 2 - scissors
   				if (compChoice == 0){
   					who_wins.setText("Rock crushes Scissors");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 1){
   					who_wins.setText("Scissors cuts Paper");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 2){
   					who_wins.setText("Scissors ties Scissors");	
   					winner_statement.setText("Tie!");
   				}
   				else if (compChoice == 3){
   					who_wins.setText("Spock smashes Scissors");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else {
   					who_wins.setText("Scissors decapitates Lizard");	
   					winner_statement.setText("You are the Winner!");
   				}
   				break;											//break to avoid infinite loop
   				
   			case 3: 											//case 3 - spock
   				if (compChoice == 0){
   					who_wins.setText("Spock vaporizes Rock");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else if (compChoice == 1){
   					who_wins.setText("Paper disproves Spock");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 2){
   					who_wins.setText("Spock smashes Scissors");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else if (compChoice == 3){
   					who_wins.setText("Spock ties Spock");	
   					winner_statement.setText("Tie!");
   				}
   				else {
   					who_wins.setText("Lizard poisons Spock");	
   					winner_statement.setText("You are the Loser!");
   				}
   				break; 											//break to avoid infinite loop
   				
   			case 4: 											//case 4 - lizard
   				if (compChoice == 0){
   					who_wins.setText("Rock crushes Lizard");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 1){
   					who_wins.setText("Lizard eats Paper");	
   					winner_statement.setText("You are the Winner!");
   				}
   				else if (compChoice == 2){
   					who_wins.setText("Scissors decapitates Lizard");	
   					winner_statement.setText("You are the Loser!");
   				}
   				else if (compChoice == 3){
   					who_wins.setText("Lizard poisons Spock");	
   					winner_statement.setText("Tie!");
   				}
   				else {
   					who_wins.setText("Lizard ties Lizard");	
   					winner_statement.setText("Tie!");
   				}
   				
   			}
   					
   		}

	}




